services:
  datasette:
    image: datasetteproject/datasette
    container_name: datasette
    restart: always
    volumes:
      - ./data/db/all_data.db
    command: ["datasette", "-h", "0.0.0.0", "-p", "8001", "./data/db/all_data.db"]
    expose:
      - "8001"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - datasette

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
