services:
  datasette:
    image: datasetteproject/datasette
    container_name: datasette
    restart: always
    volumes:
      - ./data/db/all_data.db:/data/all_data.db
    command: bash -c "datasette install datasette-plot && datasette -h 0.0.0.0 -p 8001 /data/all_data.db --setting max_returned_rows 3000"
    expose:
      - "8001"
